spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wishlist}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:abdjWic12!}
    tomcat:
      max-active: 10
      max-idle: 5
      min-idle: 2
      initial-size: 5
      remove-abandoned: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/generated-changes.xml
    enabled: true

management:
  otlp:
    tracing:
      endpoint: http://otel-collector:4317
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  jwt:
    token:
      signing:
        key: ${JWT_SIGNING_KEY}