apiVersion: 1

datasources:
  - name: Loki
    default: true
    type: loki
    access: proxy
    url: http://loki:3100

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
