apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: "X-Skip-Health-Check"
    secureJsonData:
      httpHeaderValue1: "true"

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
